### ISSUE TITLE
HTTP Error 403: Forbidden when running gym.make

### ISSUE THREAD

**Issue by tobinstultiens** [DoubleGremlin181/RubiksCubeGym#3]
When running gym.make with ``rubiks-cube-222-lbl-v0`` it gives back the message ``state file not found`` ``Downloading....``
Which results in HTTP Error 403: Forbidden.
![image](https://user-images.githubusercontent.com/22025068/142300676-91291dbd-5dd8-44bd-be29-6f2d068077d4.png)
The [link](https://storage.googleapis.com/rubiks_cube_gym/rubiks_cube_222_states_FRU.pickle) that is causing the issue.

**Comment by DoubleGremlin181** [comment]
Thanks for bringing this to my attentention.
It seems like my GCP account ran out of credits. I'll look into a fix for it

**Comment by NikEyX** [comment]
Seems still broken? Can you just take out the dependency on GCP?

**Comment by DoubleGremlin181** [comment]
I've fixed the issue. Apologies for the delay

**Comment by DoubleGremlin181** [comment]
> Seems still broken? Can you just take out the dependency on GCP?

Ideally I wanted to do that and have it generate the state file upon install. However, I was not able to figure out a way to generate the states in a deterministic manner. Therefore, I settled with making them randomly and standardizing it by integrating those files.
